version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: food
      POSTGRES_PASSWORD: foodpassword
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring
  hlt-discovery-service:
    image: ivannicksim/hlt-discovery-service:latest
    container_name: hlt-discovery-service
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - zipkin
  hlt-api-gateway-service:
    image: ivannicksim/hlt-api-gateway-service:latest
    container_name: hlt-api-gateway-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - zipkin
      - hlt-discovery-service
  hlt-food-service:
    image: ivannicksim/hlt-food-service:latest
    container_name: hlt-food-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - hlt-discovery-service
      - hlt-api-gateway-service
      - postgres
  hlt-bmr-calc-service:
    image: ivannicksim/hlt-bmr-calc-service:latest
    container_name: hlt-bmr-calc-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - zipkin
      - hlt-discovery-service
      - hlt-api-gateway-service
      - hlt-food-service
      - postgres
  hlt-bmi-calc-service:
    image: ivannicksim/hlt-bmi-calc-service:latest
    container_name: hlt-bmi-calc-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - zipkin
      - hlt-discovery-service
      - hlt-api-gateway-service
      - hlt-food-service
      - hlt-bmr-calc-service
      - postgres
  hlt-frontend-angular-service:
    image: ivannicksim/hlt-frontend-angular-service
    container_name: hlt-frontend-angular-service
    ports:
      - "4200:80"
    networks:
      - spring
    depends_on:
      - zipkin
      - hlt-discovery-service
      - hlt-api-gateway-service
      - hlt-food-service
      - hlt-bmr-calc-service
      - hlt-bmi-calc-service
      - postgres
networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge
volumes:
  postgres:
  pgadmin: