drop table if exists food ;
drop sequence if exists hibernate_sequence ;

create sequence hibernate_sequence start 1 increment 1;
create table food (
       id int8 not null,
        brand_name varchar(255) not null,
        calcium int8,
        calories int8 not null,
        cholesterol int8,
        created_date timestamp,
        description varchar(255) not null,
        fibers int8,
        iron int8,
        last_modified_date timestamp,
        mono_unsaturated_fats int8,
        omega3 int8,
        omega6 int8,
        omega9 int8,
        poly_unsaturated_fats int8,
        potassium int8,
        proteins int8,
        saturated_fats int8,
        sodium int8,
        sugars int8,
        total_carbohydrates int8,
        total_fats int8,
        trans_fats int8,
        version int8,
        vitamina int8,
        vitaminb1 int8,
        vitaminb12 int8,
        vitaminb2 int8,
        vitaminb3 int8,
        vitaminb5 int8,
        vitaminb6 int8,
        vitaminb7 int8,
        vitaminb9 int8,
        vitaminc int8,
        vitamind int8,
        vitamine int8,
        vitamink int8,
        primary key (id)
    );